### ISSUE TITLE
flaky v::io/x/ref/services/agent/internal/ipc::TestBadConnect [GoRace - linux,amd64]

### ISSUE THREAD

**Issue by cosnicolaou** [vanadium/issues#1208] opened 2016-03-02 04:39 UTC
this test is flaky in presubmits: https://dashboard.v.io/?arch=amd64&class=v.io%2Fx%2Fref%2Fservices%2Fagent%2Finternal%2Fipc&job=vanadium-go-race&n=21160&os=linux&part=1&suite=v.io%2Fx%2Fref%2Fservices%2Fagent%2Finternal%2Fipc&test=TestBadConnect+%5BGoRace+-+linux%2Camd64%5D&type=presubmit

**Comment by asimshankar** [comment] 2016-03-02 06:29
Duplicate of vanadium/build#11
Also, please file build related issues at https://github.com/vanadium/build/issues

**Closed as completed by asimshankar** 2016-03-02 06:29 UTC
