### ISSUE TITLE
Flaky deviced tests

### ISSUE THREAD

**Issue by kenashcraft** [vanadium/issues#719] opened 2015-09-10 19:52 UTC
Here are two test failures from presubmit that appear to be unrelated to the change that triggered the test trun.

v.io/x/ref/services/device/deviced/internal/impl/applife.TestLifeOfAnApp
https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/ARCH=amd64,OS=linux,TEST=vanadium-go-test/11321/

https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/11314/ARCH=amd64,OS=linux,TEST=vanadium-go-test/testReport/junit/v/io_x_ref_services_device_deviced_internal_impl_daemonreap/TestDaemonRestart__GoTest___linux_amd64_/

**Comment by caprita** [comment] 2015-10-07 20:31
Just submitted https://vanadium-review.googlesource.com/16315, which addresses one potential source of flakiness; I think it should fix https://veyron.corp.google.com/jenkins/job/vanadium-go-test/757/ARCH=amd64,OS=linux/testReport/junit/v/io_x_ref_services_device_deviced_internal_impl_reaping/TestReapReconciliationViaAppCycle__GoTest___linux_amd64_/ ( @rogulenko )  and perhaps some of the failures observed by @kenashcraft when he was build cop.

Note, the issue that's causing the flakiness reported by @suharshs is not resolved, and I believe that the root cause of that is somewhere in the rpc system.

**Comment by caprita** [comment] 2015-10-08 21:15
Also checked in https://vanadium-review.googlesource.com/#/c/16340/ which should address the flakiness observed by Suharsh in runtime/internal/rt/mgmt_test.go.

**Closed by caprita** 2015-10-08 21:15 UTC
Labels: Oncall
