### ISSUE TITLE
identityd: Running out of file descriptors

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1066] opened 2016-01-12 18:53 UTC
https://veyron.corp.google.com/jenkins/job/release-candidate-3-deploy/232/console

`error from oauth-blesser: got 500 Internal Server Error`

This affects our daily push.

@asimshankar @ankurtaly IIRC, we tried to fix this a couple days ago, but it's still happening, unfortunately.

**Comment by asimshankar** [comment] 2016-01-12 19:02
Yeah, I haven't traced the root cause of this, but for the record what's happening is that the process runs out of file descriptors because there are tons of (presumably) half-closed TCP connections lying around.

Here is a snippet of `lsof -p <pid of identityd>`:

```
bin     7526 veyron 1004u     sock                0,7      0t0 55312366 can't identify protocol
bin     7526 veyron 1005u     sock                0,7      0t0 55351463 can't identify protocol
bin     7526 veyron 1006u     sock                0,7      0t0 55355727 can't identify protocol
bin     7526 veyron 1007u     sock                0,7      0t0 55355743 can't identify protocol
bin     7526 veyron 1008u     sock                0,7      0t0 55344903 can't identify protocol
bin     7526 veyron 1009u     sock                0,7      0t0 55357491 can't identify protocol
bin     7526 veyron 1010u     sock                0,7      0t0 55347578 can't identify protocol
bin     7526 veyron 1011u     sock                0,7      0t0 55344924 can't identify protocol
bin     7526 veyron 1012u     sock                0,7      0t0 55340934 can't identify protocol
bin     7526 veyron 1013u     sock                0,7      0t0 55360565 can't identify protocol
bin     7526 veyron 1014u     sock                0,7      0t0 55330722 can't identify protocol
bin     7526 veyron 1015u     sock                0,7      0t0 55344951 can't identify protocol
bin     7526 veyron 1016u     sock                0,7      0t0 55354611 can't identify protocol
bin     7526 veyron 1017u     sock                0,7      0t0 55355843 can't identify protocol
bin     7526 veyron 1018u     sock                0,7      0t0 55356553 can't identify protocol
bin     7526 veyron 1019u     sock                0,7      0t0 55343797 can't identify protocol
bin     7526 veyron 1020u     sock                0,7      0t0 55360623 can't identify protocol
bin     7526 veyron 1021u     sock                0,7      0t0 55353660 can't identify protocol
bin     7526 veyron 1022u     sock                0,7      0t0 55333731 can't identify protocol
bin     7526 veyron 1023u     sock                0,7      0t0 55338940 can't identify protocol
```

And for reference, this is what I found about `can't identify protocol` implying sockets in [half-closed state](https://idea.popcount.org/2012-12-09-lsof-cant-identify-protocol/).

**Comment by asimshankar** [comment] 2016-01-12 20:40
FYI: The workaround for now is to bump the process and/or update the file descriptor limit of the process

**Comment by asimshankar** [comment] 2016-01-13 17:44
I think the change above worked, looking at the staging instance deployed at around 5am there are no `can't identify protocol` lines in the output of `lsof`. Will verify on the production instance once that is upgraded and then close this issue

**Comment by asimshankar** [comment] 2016-01-13 19:11
Looked at the production instance, seems to be doing well so closing this out.

For the record: My theory on why this old piece of code triggered trouble now: We recently switched to using the `gcreds` command on GCE instance to obtain credentials and that exercises the oauth-blesser HTTP endpoint much more often than before. So the leak existed earlier too, we just didn't notice because the endpoint wasn't used often enough between process restarts.

**Closed as completed by asimshankar** 2016-01-13 19:11 UTC
