### ISSUE TITLE
Syncbase Mojo Dart: Panic even after picking an account

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#893] opened 2015-11-13 23:08 UTC
Note that this happens only on the first run after picking an account. Subsequent runs are okay since the account chosen seems to be loaded properly in later runs. (The account picker doesn't show up in later runs either.)

I was on 0.0.14

@aghassemi @asadovsky 

```
I1113 23:06:04.159053    4988 mojo_blessings.go:93] Obtained OAuth2 token, will exchange for blessings
panic: runtime error: index out of range

goroutine 17 [running, locked to thread]:
mojo/public/platform/native_cgo.(*CGoSystem).ReadData(0xb683a484, 0x16, 0x1, 0x116, 0xb683a484, 0x0, 0x0)
    /usr/local/google/home/alexfandrianto/mojo/src/mojo/public/platform/native_cgo/system_cgo.go:145 +0x104
mojo/public/go/system.(*dataPipeConsumer).ReadData(0x9576f9f8, 0x1, 0x116, 0x0, 0x0, 0x0)
    /usr/local/google/home/alexfandrianto/mojo/src/mojo/public/go/system/data_pipe.go:82 +0x78
main.token2blessings(0x84e860e0, 0x95633ef0, 0x957de000, 0x49, 0x84e86788, 0x95546520, 0x0, 0x0, 0x0
, 0x0, ...)
    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/ref/services/syncbase/syncbased/mojo_blessings.go:148 +0x3ec
main.setBlessings(0x957bfac0, 0x84e860e0, 0x95633ef0, 0x0, 0x0)
    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/ref/services/syncbase/syncbased/mojo_blessings.go:95 +
0x100
main.(*delegate).Initialize(0x956ce3c0, 0x84e860e0, 0x95633ef0)
    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/ref/services/syncbase/syncbased/mojo_main.go:42 +0x9c
mojo/public/go/application.(*ApplicationImpl).Initialize(0x95633ef0, 0x84e81fb0, 0x95546318, 0x956c39d0, 0x956ce4e0, 0x2b,
0x0, 0x0)
    /usr/local/google/home/alexfandrianto/mojo/src/mojo/public/go/application/application_impl.go:101 +0x16c
mojo/public/interfaces/application/application.(*application_Stub).Accept(0x956c39b0, 0x95599880, 0x0, 0x0)
    /usr/local/google/home/alexfandrianto/mojo/src/out/Debug/gen/go/src/mojo/public/interfaces/application/application/application.mojom.go:673 +0x2fc
mojo/public/go/bindings.(*Stub).ServeRequest(0x956d5820, 0x0, 0x0)
    /usr/local/google/home/alexfandrianto/mojo/src/mojo/public/go/bindings/stub.go:48 +0x98
mojo/public/go/application.Run(0x84e81ec0, 0x956ce3c0, 0x4)
    /usr/local/google/home/alexfandrianto/mojo/src/mojo/public/go/application/application_impl.go:83 +0x228
main.MojoMain(0x4, 0xbee5b35c)
    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/ref/services/syncbase/syncbased/mojo_main.go:79 +0xa4

goroutine 40 [syscall, locked to thread]:
mojo/public/platform/native_cgo._Cfunc_MojoWaitMany(0x957bdce0, 0x957bdce4, 0x1, 0xffffffff, 0xffffffff, 0x957bdce8, 0x957bdcf0, 0x0)
    ??:0 +0x38
mojo/public/platform/native_cgo.(*CGoSystem).WaitMany(0xb683a484, 0x957bdce0, 0x1, 0x1, 0x957bdce4, 0x1, 0x1, 0xffffffff, 0xffffffff, 0x0, ...)
    /usr/local/google/home/alexfandrianto/mojo/src/mojo/public/platform/native_cgo/system_cgo.go:190 +0x22c
mojo/public/go/system.(*coreImpl).WaitMany(0xb683a4b8, 0x957bdba0, 0x1, 0x2, 0x957bdbb0, 0x1, 0x2, 0xffffffff, 0xffffffff, 0x0, ...)
    /usr/local/google/home/alexfandrianto/mojo/src/mojo/public/go/system/core.go
:100 +0x2b0
mojo/public/go/bindings.(*asyncWaiterWorker).runLoop(0x95633f40)
    /usr/local/google/home/alexfandrianto/mojo/src/mojo/public/go/bindings/async_waiter.go:177 +0x100
created by mojo/public/go/bindings.newAsyncWaiter
    /usr/local/google/home/alexfandrianto/mojo/src/mojo/public/go/bindings/async_waiter.go:245 +0x590
```

**Comment by afandria** [comment] 2015-11-13 23:17
Actually, this doesn't always happen. I wouldn't prioritize this bug, unless other people see this too.

**Comment by asimshankar** [comment] 2015-11-14 00:32
Took a quick look and didn't find anything easy. Since you mentioned that I shouldn't prioritize this, am not planning to look into it soon unless you tell me otherwise.

Note that the account picker will show up just once right now - once you pick an account the same one stays for future runs. Do you have logs from subsequent runs that didn't crash - they should dump out the  blessing being used.

**Comment by asimshankar** [comment] 2015-11-19 01:34
Duplicate of domokit/modular#351

**Closed as completed by asimshankar** 2015-11-19 01:34 UTC
