### ISSUE TITLE
kill_tut_process on macos should not use "wait -n"

### ISSUE THREAD

**Issue by jeffallen** [vanadium/issues#1057] opened 2016-01-10 16:48 UTC
Seen while doing tutorials:

$ kill_tut_process TUT_PID_SERVER
-bash: wait: -n: invalid option

I don't know what "wait -n" does, but MacOS doesn't need it.

**Comment by afandria** [comment] 2016-01-11 21:06
Thanks for reporting this. I can confirm that it doesn't error on Linux but does on OS X.

@monopole @jxson
In `www/content/tutorials/setup.md`, we define `kill_tut_process` with `wait -n`, but I do not know what the `-n` flag adds. Superficially, the behavior seems to be the same even without the flag.

EDIT: https://www.gnu.org/software/bash/manual/html_node/Job-Control-Builtins.html describes what `-n` does, and it does not look like it's necessary since we only call wait with a single pid.

**Comment by monopole** [comment] 2016-01-11 22:16
fixed by  https://vanadium-review.googlesource.com/#/c/18970/

It's going to be a little while before these changes autopush to v.io

Thanks for the reports @jeffallen

**Closed as completed by monopole** 2016-01-11 22:16 UTC
