### ISSUE TITLE
Use of ctx variable never explained

### ISSUE THREAD

**Issue by zanesterling** [vanadium/issues#1347] opened 2016-06-01 19:40 UTC
CC @aghassemi

In the tutorials, the line `ctx, shutdown := v23.Init()` is common.
The use of `shutdown` can be inferred from naming and context, but the `ctx` variable is often used and never explained.
Perhaps add a section in Concepts for this?

**Comment by ghost** [comment] 2016-06-01 19:44
This is a known issue.  In the syncbase APIs the context isn't surfaced, and that's where I'm focused right now.

**Comment by aghassemi** [comment] 2016-06-01 19:55
Yes, agree but a known issue: https://github.com/vanadium/issues/issues/1142 

Closing: Duplicate of https://github.com/vanadium/issues/issues/1142

**Closed as completed by aghassemi** 2016-06-01 19:55 UTC
Labels: Documentation, Area: Website
