### ISSUE TITLE
vclockd: DoNtpUpdate: failed to fetch NTP time: vclock: NtpSync: no NTP server

### ISSUE THREAD

**Issue by bprosnitz** [vanadium/issues#1036] opened 2016-01-04 23:35 UTC
I saw this error while running the go-cover test https://veyron.corp.google.com/jenkins/job/vanadium-go-cover/1355/testReport/junit/v/io_v23_syncbase/TestAppDestroyAndRecreate/ 

``````
        I0104 15:20:05.389835   22565 funcs.go:22] Using permissions: {"Admin":{"In":["root:client"],"NotIn":null},"Debug":{"In":["root:client"],"NotIn":null},"Read":{"In":["root:client"],"NotIn":null},"Resolve":{"In":["root:client"],"NotIn":null},"Write":{"In":["root:client"],"NotIn":null}}
E0104 15:20:05.403908   22565 funcs.go:94] vclockd: DoNtpUpdate: failed to fetch NTP time: vclock: NtpSync: no NTP server
F0104 15:20:05.521574   22565 funcs.go:116] sync: processWatchLogBatch: a, d: watcher cannot process batch: syncbase.test: Canceled: closed store
goroutine 1063 [running]:
github.com/cosnicolaou/llog.stacks(0xc82022c100, 0x418000, 0x0, 0x0, 0x0)
    /home/veyron/jenkins/workspace/vanadium-go-cover/root/third_party/go/src/github.com/cosnicolaou/llog/glog.go:914 +0xa7
github.com/cosnicolaou/llog.(*Log).output(0xc8200aaa00, 0xc800000003, 0xc82009e540, 0x12ffff0, 0x8, 0x74)
    /home/veyron/jenkins/workspace/vanadium-go-cover/root/third_party/go/src/github.com/cosnicolaou/llog/glog.go:868 +0x221
github.com/cosnicolaou/llog.(*Log).PrintfDepth(0xc8200aaa00, 0xc800000003, 0x1, 0xfa18a0, 0x44, 0xc8205bec90, 0x3, 0x3)
    /home/veyron/jenkins/workspace/vanadium-go-cover/root/third_party/go/src/github.com/cosnicolaou/llog/glog.go:827 +0x1d3
github.com/cosnicolaou/llog.(*Log).Printf(0xc8200aaa00, 0x3, 0xfa18a0, 0x44, 0xc8205bec90, 0x3, 0x3)
    /home/veyron/jenkins/workspace/vanadium-go-cover/root/third_party/go/src/github.com/cosnicolaou/llog/glog.go:803 +0x64
github.com/cosnicolaou/llog.(*Log).Printf-fm(0xc800000003, 0xfa18a0, 0x44, 0xc8205bec90, 0x3, 0x3)
    /home/veyron/jenkins/workspace/vanadium-go-cover/root/release/go/src/v.io/x/lib/vlog/funcs.go:21 +0x5a
v.io/x/lib/vlog.Fatalf(0xfa18a0, 0x44, 0xc8205bec90, 0x3, 0x3)
    /home/veyron/jenkins/workspace/vanadium-go-cover/root/release/go/src/v.io/x/lib/vlog/funcs.go:116 +0x7a
v.io/x/ref/services/syncbase/vsync.(*syncService).processWatchLogBatch(0xc82047a840, 0xc820596690, 0xc82063de20, 0x1, 0xc820460b92, 0x1, 0x7fd3f46b5a80, 0xc8205b1480, 0xc82038e0a8, 0x0, ...)
    /home/veyron/jenkins/workspace/vanadium-go-cover/root/release/go/src/v.io/x/ref/services/syncbase/vsync/watcher.go:206 +0x89f
v.io/x/ref/services/syncbase/vsync.(*syncService).processDatabase(0xc82047a840, 0xc820596690, 0xc82063de20, 0x1, 0xc820460b92, 0x1, 0x7fd3f46b5a80, 0xc8205b1480, 0x8000100)
    /home/veyron/jenkins/workspace/vanadium-go-cover/root/release/go/src/v.io/x/ref/services/syncbase/vsync/watcher.go:132 +0x970
v.io/x/ref/services/syncbase/vsync.(*syncService).processStoreUpdates.func1(0xc82063de20, 0x1, 0xc820460b92, 0x1, 0x7fd3f46b5a80, 0xc8205b1480, 0x7fd3f46b5b90)
    /home/veyron/jenkins/workspace/vanadium-go-cover/root/release/go/src/v.io/x/ref/services/syncbase/vsync/watcher.go:83 +0x81
v.io/x/ref/services/syncbase/vsync.(*syncService).forEachDatabaseStore(0xc82047a840, 0xc820596690, 0xc8206efe30)
    /home/veyron/jenkins/workspace/vanadium-go-cover/root/release/go/src/v.io/x/ref/services/syncbase/vsync/util.go:60 +0x9ca
v.io/x/ref/services/syncbase/vsync.(*syncService).processStoreUpdates(0xc82047a840, 0xc820596690)
    /home/veyron/jenkins/workspace/vanadium-go-cover/root/release/go/src/v.io/x/ref/services/syncbase/vsync/watcher.go:88 +0x80
v.io/x/ref/services/syncbase/vsync.(*syncService).watchStore(0xc82047a840, 0xc820596690)
    /home/veyron/jenkins/workspace/vanadium-go-cover/root/release/go/src/v.io/x/ref/services/syncbase/vsync/watcher.go:65 +0x1bd
created by v.io/x/ref/services/syncbase/vsync.New
    /home/veyron/jenkins/workspace/vanadium-go-cover/root/release/go/src/v.io/x/ref/services/syncbase/vsync/sync.go:216 +0x89e
      ```
``````

**Comment by asadovsky** [comment] 2016-01-05 04:00
That particular message is expected - we disable NTP in tests since it involves contacting a third-party server:
https://github.com/vanadium/go.ref/blob/master/services/syncbase/server/service.go#L192

The test must be failing for some other reason. @ivanpi-mtv wrote this test recently, so I'm assigning to him to investigate.

**Comment by ivanpi-mtv** [comment] 2016-01-07 02:11
Duplicate of #1021

**Closed as completed by ivanpi-mtv** 2016-01-07 02:11 UTC
Labels: Area: Syncbase
