### ISSUE TITLE
Error during vanadium install: autoreconf not found

### ISSUE THREAD

**Issue by zanesterling** [vanadium/issues#1346] opened 2016-06-01 16:24 UTC
cc @asadovsky

Encountered errors:

```
ERROR: util.go:70: Build and install Snappy: syncbase.go:358: Last("autoreconf", "--install", "--force", "--verbose"): exec: "autoreconf": executable file not found in $PATH
Install: v23:base amd64-linux@5: util.go:70: Build and install Snappy: syncbase.go:358: Last("autoreconf", "--install", "--force", "--verbose"): exec: "autoreconf": executable file not found in $PATH
ERROR: profile_manager.go:235: Last("jiri", "profile-v23", "install", "--profiles-db=/usr/local/google/home/zsterling/vanadium/.jiri_root/profile_db", "--profiles-dir=.jiri_root/profiles", "--target=amd64-linux@", "--force=false", "v23:base"): exit status 1
```

Googled “autoreconf not found”, was told to install autoconf.
That worked, but it would be nice if the [https://vanadium.github.io/installation/](install script) checked for the existence of autoconf and gave a more informative error message.
Alternatively, we could mention it in the [https://vanadium.github.io/installation/step-by-step.html](step-by-step instructions).

**Comment by asadovsky** [comment] 2016-06-01 16:41
I think something may have changed recently with which things are installed automatically vs. required as prereqs. Re-assigning to Nick who I believe is familiar with this. Hopefully we just need to tweak the wording to clarify the installation procedure.

**Comment by nlacasse** [comment] 2016-06-01 16:54
This happens during the profile installation.  `jiri profile install foo` used to install all required packages, using `sudo apt-get ...` or `sudo brew install ...` under the hood.  However, security folks complained about our binaries calling `sudo`.

Now, instead of calling `sudo`, there is a new command that will tell you how to install any required packages:  `jiri profile os-packages v23:base`

The step-by-step instructions correctly tell you to run that command, and run the resulting output as root.

The problem is that the main installation script runs that command, but does not run the output, so the prereqs do not get installed.

Solving this is a bit tricky because the main install script is just a concatenation of the step-by-step instructions.  I could add the following line to the step-by-step instructions (with commentary); `sudo $(jiri profile os-packages v23:base)`

**Comment by asadovsky** [comment] 2016-06-01 17:06
Yeah, seems we should either include the "sudo ..." line in the
step-by-step instructions (so that it's pulled into the single-shot
script), or update the "simple install" page to explain the prereqs. The
current state is broken, in any case.

--Adam

**Comment by nlacasse** [comment] 2016-06-01 17:19
v.io/c/22797

**Closed as completed** 2016-06-01 17:41 UTC
Labels: Area: Website, Bug
