### ISSUE TITLE
vanadium-mojo-v23proxy-integration-test and vanadium-mojo-syncbase-test flaky

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#1174] opened 2016-02-26 17:48 UTC
Looks like perhaps a Jenkins configuration issue?
+cc @afandria @aghassemi 

https://dashboard.v.io/?arch=amd64&class=vanadium-mojo-syncbase-test&job=vanadium-mojo-syncbase-test&n=20763&os=linux&part=0&suite=vanadium-mojo-syncbase-test&test=Make+test&type=presubmit

https://dashboard.v.io/?arch=amd64&class=vanadium-mojo-v23proxy-integration-test&job=vanadium-mojo-v23proxy-integration-test&n=20763&os=linux&part=0&suite=vanadium-mojo-v23proxy-integration-test&test=Make+test-integration&type=presubmit

```
[08:35:03.13] >> /usr/bin/make test-integration
[08:35:03.93] >> FAILED
../shared/mojo.mk:95: *** profile mojo not installed for target amd64-linux. Run "jiri v23-profile install --target=amd64-linux mojo".  Stop.
Current Directory: /home/veyron/jenkins/root/0/release/mojo/v23proxy
../shared/mojo.mk:95: *** profile mojo not installed for target amd64-linux. Run "jiri v23-profile install --target=amd64-linux mojo".  Stop.
Make test-integration: makefile.go:47
makefile.go:39: Last("make", "test-integration"): exit status 2
```

**Comment by aghassemi** [comment] 2016-02-26 18:00
I think issues is "jiri v23-profile list" no longer prints out targets which the `mojo/shared/mojo.mk` depends on to ensure mojo profile for the particular target is installed.

**Comment by nlacasse** [comment] 2016-02-26 18:04
Yeah, the mojo profile is definitely being installed, as the console shows:

```
Running: jiri -v v23-profile install mojo
jiri -v v23-profile install mojo: success
```

This may be caused by the transition from `jiri v23-profile` to `jiri profile-v23`.

I'll investigate further.

**Comment by aghassemi** [comment] 2016-02-26 18:23
should be fixed by https://vanadium-review.googlesource.com/#/c/20221/

**Closed as completed by aghassemi** 2016-02-26 18:23 UTC
