### ISSUE TITLE
vanadium-go-test failing in deviced

### ISSUE THREAD

**Issue by monopole** [vanadium/issues#710] opened 2015-09-04 21:37 UTC
https://veyron.corp.google.com/jenkins/job/vanadium-go-test/ARCH=amd64,OS=linux/517/console

14:21:19 fail v.io/x/ref/services/device/deviced/internal/impl/perms
14:21:19 === RUN   TestDebugPermissionsPropagation
14:21:19 ---- Shell Cleanup ----
14:21:19 ---- Cleanup calling Shutdown on program "impl/utiltest/modules.go:56 DeviceManager"
14:21:19 I0904 14:21:11.915155   22109 starter.go:194] Unclaimed device manager (/@6@tcp@127.0.0.1:41902@@f3bb3a246adb5f3c6d2de4e5662e1210@s@root/self/child@@) with public_key: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE_Nn2L-GOC4nRzP3t9-KlD_fU70rsWM8Jl8FDTnfQDhl_5KB6Mr3uMtjA82F21ICXt1EGAHYi54_YjuzuH3GHZQ==
14:21:19 I0904 14:21:11.919465   22109 helpers.go:740] Changing namespace roots from [/@6@wsh@127.0.0.1:50919@@dd5934cb2e0773b99741f889f44e42bf@m@root/self/child@@] to [/@6@wsh@127.0.0.1:50919@@dd5934cb2e0773b99741f889f44e42bf@m@@@]
14:21:19 I0904 14:21:11.996953   22109 claim.go:112] Device claimed and Permissions set to: map[Admin:{[root/$ root/self/$ root/self/mydevice/$] []} Read:{[root/$ root/self/$ root/self/mydevice/$] []} Write:{[root/$ root/self/$ root/self/mydevice/$] []} Debug:{[root/$ root/self/$ root/self/mydevice/$] []} Resolve:{[root/$ root/self/$ root/self/mydevice/$] []}]
14:21:19 I0904 14:21:11.997162   22109 starter.go:164] Stopping claimable server...
14:21:19 I0904 14:21:12.001150   22109 starter.go:166] Stopped claimable server.
14:21:19 I0904 14:21:12.001169   22109 starter.go:220] Starting claimed device services...
14:21:19 I0904 14:21:12.001210   22109 starter.go:232] Starting mount table...
14:21:19 I0904 14:21:12.003335   22109 servers.go:41] Mount table service at: "" endpoint: /@6@tcp@127.0.0.1:58100@@22c6c06dba21b31fe962fdd7f7d2c76c@m@root/self/mydevice@@
14:21:19 I0904 14:21:12.003355   22109 starter.go:313] Local mounttable (/@6@tcp@127.0.0.1:58100@@22c6c06dba21b31fe962fdd7f7d2c76c@m@root/self/mydevice@@) published as ""
14:21:19 I0904 14:21:12.003365   22109 starter.go:238] Started mount table.
14:21:19 I0904 14:21:12.003373   22109 starter.go:246] Starting proxy service...
14:21:19 I0904 14:21:12.003493   22109 starter.go:253] Started proxy service.
14:21:19 I0904 14:21:12.003504   22109 starter.go:255] Starting device service...
14:21:19 I0904 14:21:12.032742   22109 starter.go:358] Device manager (/@6@tcp@127.0.0.1:39300@@f2368e05815059e1e686b4fd62e979ca@s@root/self/mydevice@@) published as dm
14:21:19 I0904 14:21:12.032765   22109 starter.go:263] Started device service.
14:21:19 I0904 14:21:12.032810   22109 starter.go:273] Started claimed device services.
14:21:19 E0904 14:21:13.254591   22109 helper_manager.go:136] failed calling helper with args ([--chown --username veyron /home/veyron/tmp/vanadium-go-test/311985985/devicemanager511853071/app-mOhoGvjp1lPhISJUM1OyUQ/installation-20150904-21:21:12.1123/instances/instance-20150904-21:21:13.1870]):exit status 255

**Comment by caprita** [comment] 2015-10-08 21:26
Checked in https://vanadium-review.googlesource.com/#/c/16313/ yesterday. The particular failure in this bug looks like something caused by the race fixed by cl 16313, so closing this issue optimistically.

**Closed by caprita** 2015-10-08 21:26 UTC
Labels: Lang: Go
